name: "Develop CI/CD Pipeline"

on:
  pull_request:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Integração Continua (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuração do Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Configuração do Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Buildar o projeto
        run: ./gradlew build

      - name: Executar os testes unitários
        run: ./gradlew test

  build_and_push_docker:
    name: Construção do pacote
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Criar imagem Docker
        run: docker build -t kreverson/dev-fastfood-api:${{ github.sha }} .

      - name: Logar no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Armazenar imagem no Docker Hub
        run: docker push kreverson/dev-fastfood-api:${{ github.sha }}

  deploy:
    if: false
    name: Entrega Contínua (CD)
    runs-on: ubuntu-latest
    needs: build_and_push_docker

    steps:
      - name: Aplicar pacote no ambiente
        uses: ./.github/workflows/terraform.yml
        with:
          environment: dev
          docker_image_url: kreverson/dev-fastfood-api:${{ github.sha }}
          aws-assume-role-arn: "arn:aws:iam::011528262719:oidc-provider/token.actions.githubusercontent.com"
          aws-region: "us-east-2"
          aws-statefile-s3-bucket: "kreverson-us-east-2-terraform-statefile"
          aws-lock-dynamodb-table: "kreverson-us-east-2-terraform-lock"