name: "Main CI/CD Pipeline"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run Unit Tests and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run Unit Tests
        run: ./gradlew clean test

  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t kreverson/prd-fastfood-api:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push kreverson/prd-fastfood-api:${{ github.sha }}

  deploy:
    if: false
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      docker_image_url: kreverson/prd-fastfood-api:${{ github.sha }}
      aws-assume-role-arn: "arn:aws:iam::011528262719:oidc-provider/token.actions.githubusercontent.com"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "kreverson-us-east-2-terraform-statefile"
      aws-lock-dynamodb-table: "kreverson-us-east-2-terraform-lock"